[build]
  base = "cms"
  command = "npm run seed && npm run seed:blog"
  publish = "public"

[functions]
  directory = "cms/netlify/functions"
  external_node_modules = ["express", "ejs", "express-session", "session-file-store", "bcryptjs", "helmet", "multer", "serverless-http"]
  node_bundler = "esbuild"

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/server/:splat"
  status = 200
  force = true

[build.environment]
  NODE_VERSION = "20"
